### ISSUE TITLE
Chile data not correct

### ISSUE THREAD

**Issue by javierconcha** [HuidaeCho/covid-19#10]
Hello Huidae,

The numbers for Chile are not correct. It shows that the last update happened on April 20. Also, it shows the wrong number of deaths for the Chile and the Valparaiso province.

**Comment by HuidaeCho** [comment]
They changed the format. Looking into it.

**Comment by HuidaeCho** [comment]
No... not actually. Maybe it was my internet connection a couple days ago? Valparaiso had an empty line in the data file. That caused the issue.
