### ISSUE TITLE
Data and Map not showing

### ISSUE THREAD

**Issue by javierconcha** [HuidaeCho/covid-19#11]
Hello Huidae,
For some reason, the maps and numbers are not showing on your website. The same is happening in my mine. Do you know why?

**Comment by HuidaeCho** [comment]
It's working right now. It can be slow because of the size of data.

**Comment by javierconcha** [comment]
It is really weird because it is indeed working for my users but the map and data do not load in any of my machines nor in my cell phone. I tried in different browsers as well (Chrome and Safari).

**Comment by HuidaeCho** [comment]
Please check your dev console in the browser. You can see any error messages from Javascript, if any.

**Comment by javierconcha** [comment]
I will check that later. 

As for now, I continue having the same problem. I have checked with people in Italy and they have the same problem. People in Chile can see it correctly though. I'm wondering if it is a region issue with logging/downloading/retrieving the map. Same behavior for your website and mine in Italy and Germany.

**Comment by javierconcha** [comment]
From my dev console in Chrome:

> Uncaught ReferenceError: $ is not defined
    at ol-ext.min.js:9
index.html:532 Uncaught TypeError: ol.Overlay.Popup is not a constructor
    at index.html:532
DevTools failed to load SourceMap: Could not load content for chrome-extension://hdokiejnpimakedhajhdlcegeplioahd/sourcemaps/onloadwff.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

**Comment by HuidaeCho** [comment]
Getting the same error here. I think ol-ext.min.js is somehow broken. I may have to copy their previous version locally.

**Comment by HuidaeCho** [comment]
Fixed in my repo. You need to download https://github.com/Viglino/ol-ext/archive/v3.1.11.zip and uncompress it in the same folder as *.html.

**Comment by HuidaeCho** [comment]
Please check it again. It wasn't a good idea to use their dev version of the script.

**Comment by javierconcha** [comment]
Issue solved! Thanks!
