### ISSUE TITLE
Minsal changed the display of the data again

### ISSUE THREAD

**Issue by javierconcha** [HuidaeCho/covid-19#12]
Hey Huidae,
Just to let you know, Minsal changed the order of the columns in the table again. I guess this is why the Chile data is not showing correctly.

**Comment by HuidaeCho** [comment]
yes, their data takes a lot of maintenance. They added more columns and started mixing periods and commas in percents.

**Comment by javierconcha** [comment]
I feel your pain. Believe me.

**Comment by HuidaeCho** [comment]
Fixed
