### ISSUE TITLE
https://app.isnew.info/covid-19/ seems to be broken

### ISSUE THREAD

**Issue by akuckartz** [HuidaeCho/covid-19#13]
The map is empty and no numbers are shown in the right column.

**Comment by HuidaeCho** [comment]
Thanks for the report. It just takes time to load and draw all data. About 13 seconds on my browser. There are just too many affected counties in the US. Please try it again.

**Comment by akuckartz** [comment]
I tried again. After about 1-2 minutes the information finally became visible! Some visible indicator during that time would be helpful :-)
