### ISSUE TITLE
New feature: Plotting CFR or Daily Increases

### ISSUE THREAD

**Issue by javierconcha** [HuidaeCho/covid-19#6]
Hey Huidae,
It would be nice to have a way to switch the CFR plot to other plots, like daily increases, for instance. Just an idea. Something that would be useful for my adaptation of your code:

[https://github.com/javierconcha/covid-19-Chile](https://github.com/javierconcha/covid-19-Chile)

Thanks!

**Comment by HuidaeCho** [comment]
Please check https://github.com/HuidaeCho/covid-19/commit/4b738d53fe2cc34a8e0647064c1d31e994211813. It's available [here](https://app.isnew.info/covid-19/).

**Comment by javierconcha** [comment]
Excellent! Thank you so much!!!

**Comment by HuidaeCho** [comment]
Enjoy!
